### ISSUE TITLE
error with debian build

### ISSUE THREAD

**Issue by chrisberesford** [geopython/mapslicer#22]
I'm seeing an error whilst trying to build a .deb, please could you take a look, Thanks, Chris.

chris@venus:~/mapslicer/mapslicer-master$ ./deploy/linux/makedeb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "mapslicer/__init__.py", line 3, in <module>
    from main import MainFrame
  File "mapslicer/main.py", line 11, in <module>
    import wizard
  File "mapslicer/wizard.py", line 13, in <module>
    from wxgdal2tiles import wxGDAL2Tiles
  File "mapslicer/wxgdal2tiles.py", line 8, in <module>
    from gdal2tiles import GDAL2Tiles
  File "mapslicer/gdal2tiles.py", line 38, in <module>
    from osgeo import gdal
ImportError: No module named osgeo
mapslicer.py
mapslicer/
mapslicer/widgets.py
mapslicer/icons.py
mapslicer/preprocess.py
mapslicer/gdal2tiles.py
mapslicer/wizard.py
mapslicer/__init__.py
mapslicer/pp/
mapslicer/pp/pptransport.py
mapslicer/pp/__init__.py
mapslicer/pp/ppworker.py
mapslicer/pp/ppserver.py
mapslicer/pp/ppauto.py
mapslicer/gdalpreprocess.py
mapslicer/main.py
mapslicer/wxgdal2tiles.py
mapslicer/config.py
README.txt
deploy/linux/mapslicer.desktop
resources/icon.png
dpkg-buildpackage: warning:     debian/changelog(l1): badly formatted heading line
LINE: mapslicer () unstable; urgency=low
dpkg-buildpackage: warning:     debian/changelog(l2): found blank line where expected first heading
dpkg-buildpackage: warning:     debian/changelog(l3): found change data where expected first heading
LINE:   * Release. 
Can't call method "as_string" on an undefined value at /usr/share/perl5/Dpkg/Changelog.pm line 249.
cp: cannot stat '/tmp/tmp.6N4xDoAez3/*.deb': No such file or directory

**Comment by kalxas** [comment]
The debian build script is not maintained. What is your target OS?

**Comment by johanvdw** [comment]
Probably you can fix the build by replacing the variables in the
debian/changelog files yourself.

**Comment by chrisberesford** [comment]
I'm trying to build it on Ubuntu 16.04 LTS. If I can use mapslicer without building the deb then I would be happy to do that.

I did plenty of googling and found a similar suggestion re: changing the changelog files, but not enough detail to allow me to do it. I'm not an expert by any stretch with building debs.

**Comment by kalxas** [comment]
Please see how we install Mapslicer for OSGeo-Live:
https://github.com/OSGeo/OSGeoLive/blob/master/bin/install_mapslicer.sh

I hope this helps.

**Comment by johanvdw** [comment]
Check:

https://github.com/johanvdw/mapslicer/commit/0c120349b3a7741dd586f2119c43ff7e40163a90

**Comment by answerquest** [comment]
Some other errors coming now:
```
./deploy/linux/makedeb 
mapslicer.py
mapslicer/
mapslicer/wxgdal2tiles.py
mapslicer/icons.py
mapslicer/widgets.py
mapslicer/pp/
mapslicer/pp/ppauto.py
mapslicer/pp/ppserver.py
mapslicer/pp/ppworker.py
mapslicer/pp/pptransport.py
mapslicer/pp/__init__.py
mapslicer/config.py
mapslicer/preprocess.py
mapslicer/wizard.py
mapslicer/gdalpreprocess.py
mapslicer/main.py
mapslicer/gdal2tiles.py
mapslicer/__init__.py
README.txt
deploy/linux/mapslicer.desktop
resources/icon.png
dpkg-buildpackage: info: source package mapslicer
dpkg-buildpackage: info: source version 1.0~rc1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Angelos Tzotsos <**redacted**>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build MapSlicer-1.0~rc1
 debian/rules clean
dh_testdir
make: dh_testdir: Command not found
debian/rules:17: recipe for target 'clean' failed
make: *** [clean] Error 127
dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2
cp: cannot stat '/tmp/tmp.MhqcvCvbH2/*.deb': No such file or directory
```
